Unlocked: false
Url: wss://lighthouse.uni-kiel.de/websocket
User: Lighthouse
Token: API-TOK_CKXz-mYlh-38Hb-9pWa-UvXI
# Color-Correction:
# IMPORTANT NOTE: before changing the color correction, make sure that the maximum value (100% white)
# does not exceed the current limit at the lamps (2A) after correction, otherwise the fuse will trip
# Correction values:
# Old lamp server (r,g,b): 256/256, 134/256, 54/256
# FastLED C++ library (r,g,b): 256/256, 176/256, 240/256
# New tested correction factor (I < 2A per lamp):
# TODO: test color correction live
ColorCorrectionRed: 1.0
ColorCorrectionGreen: 0.3 # 0.52 # 0.65
ColorCorrectionBlue: 0.2 # 0.21 # 0.55
EnableMetrics: true
SendMetricsToBeacon: true
MetricsBeaconPath: ["metrics", "laser"]
WriteMetricsToFile: true
MetricsFilePath: "statusLamps.json"
WriteRespondingToFile: true
RespondingFilePath: "./statusRooms.txt"
PingDelaySeconds: 1
MonitoringIntervalSeconds: 1
MaxPingsWithoutResponse: 3
ResponseDeadlineMs: 1000
Debug: false
RateLimitFPS: 60
Clients:
  # 14th floor
  - { room: "1413",  ip: "192.168.1.1",   startIdx: 0,   numLamps: 2, apiVersion: 1 }
  - { room: "1412",  ip: "192.168.1.2",   startIdx: 2,   numLamps: 4, apiVersion: 1 }
  - { room: "1411",  ip: "192.168.1.3",   startIdx: 6,   numLamps: 3, apiVersion: 1 }
  - { room: "1410a", ip: "192.168.1.4",   startIdx: 9,   numLamps: 2, apiVersion: 1 }
  - { room: "1410",  ip: "192.168.1.5",   startIdx: 11,  numLamps: 2, apiVersion: 1 }
  - { room: "1409",  ip: "192.168.1.6",   startIdx: 13,  numLamps: 2, apiVersion: 1 }
  - { room: "1408",  ip: "192.168.1.7",   startIdx: 15,  numLamps: 3, apiVersion: 1 }
  - { room: "1407a", ip: "192.168.1.8",   startIdx: 18,  numLamps: 2, apiVersion: 1 }
  - { room: "1407",  ip: "192.168.1.9",   startIdx: 20,  numLamps: 2, apiVersion: 1 }
  - { room: "1406",  ip: "192.168.1.10",  startIdx: 22,  numLamps: 2, apiVersion: 1 }
  - { room: "1406a", ip: "192.168.1.11",  startIdx: 24,  numLamps: 2, apiVersion: 1 }
  - { room: "1405",  ip: "192.168.1.12",  startIdx: 26,  numLamps: 2, apiVersion: 1 }
  # 13th floor
  - { room: "1316",  ip: "192.168.1.13",  startIdx: 28,  numLamps: 3, apiVersion: 2 }
  - { room: "1315",  ip: "192.168.1.14",  startIdx: 31,  numLamps: 3, apiVersion: 2 }
  - { room: "1314",  ip: "192.168.1.15",  startIdx: 34,  numLamps: 3, apiVersion: 2 }
  - { room: "1313",  ip: "192.168.1.16",  startIdx: 37,  numLamps: 3, apiVersion: 2 }
  - { room: "1312",  ip: "192.168.1.17",  startIdx: 40,  numLamps: 3, apiVersion: 2 }
  - { room: "1311",  ip: "192.168.1.18",  startIdx: 43,  numLamps: 3, apiVersion: 2 }
  - { room: "1310",  ip: "192.168.1.19",  startIdx: 46,  numLamps: 2, apiVersion: 2 }
  - { room: "1309",  ip: "192.168.1.20",  startIdx: 48,  numLamps: 2, apiVersion: 2 }
  - { room: "1308",  ip: "192.168.1.21",  startIdx: 50,  numLamps: 4, apiVersion: 2 }
  - { room: "1307",  ip: "192.168.1.22",  startIdx: 54,  numLamps: 2, apiVersion: 2 }
  # 12th floor
  - { room: "1217",  ip: "192.168.1.23",  startIdx: 56,  numLamps: 4, apiVersion: 2 }
  - { room: "1216",  ip: "192.168.1.24",  startIdx: 60,  numLamps: 3, apiVersion: 2 }
  - { room: "1215",  ip: "192.168.1.25",  startIdx: 63,  numLamps: 3, apiVersion: 2 }
  - { room: "1214",  ip: "192.168.1.26",  startIdx: 66,  numLamps: 2, apiVersion: 2 }
  - { room: "1213",  ip: "192.168.1.27",  startIdx: 68,  numLamps: 3, apiVersion: 2 }
  - { room: "1212",  ip: "192.168.1.28",  startIdx: 71,  numLamps: 3, apiVersion: 2 }
  - { room: "1211",  ip: "192.168.1.29",  startIdx: 74,  numLamps: 3, apiVersion: 2 }
  - { room: "1210L", ip: "192.168.1.30",  startIdx: 77,  numLamps: 4, apiVersion: 2 }
  - { room: "1210R", ip: "192.168.1.31",  startIdx: 81,  numLamps: 3, apiVersion: 2 }
  # 11th floor
  - { room: "1118",  ip: "192.168.1.32",  startIdx: 84,  numLamps: 3, apiVersion: 2 }
  - { room: "1117",  ip: "192.168.1.33",  startIdx: 87,  numLamps: 4, apiVersion: 2 }
  - { room: "1116",  ip: "192.168.1.34",  startIdx: 91,  numLamps: 3, apiVersion: 2 }
  - { room: "1115",  ip: "192.168.1.35",  startIdx: 94,  numLamps: 5, apiVersion: 2 }
  - { room: "1114",  ip: "192.168.1.37",  startIdx: 99,  numLamps: 4, apiVersion: 2 }
  - { room: "1113",  ip: "192.168.1.38",  startIdx: 103, numLamps: 3, apiVersion: 2 }
  - { room: "1112",  ip: "192.168.1.39",  startIdx: 106, numLamps: 3, apiVersion: 2 }
  - { room: "1111",  ip: "192.168.1.40",  startIdx: 109, numLamps: 3, apiVersion: 2 }
  # 10th floor
  - { room: "1019",  ip: "192.168.1.41",  startIdx: 112, numLamps: 3, apiVersion: 2 }
  - { room: "1018",  ip: "192.168.1.42",  startIdx: 115, numLamps: 2, apiVersion: 2 }
  - { room: "1017",  ip: "192.168.1.43",  startIdx: 117, numLamps: 2, apiVersion: 2 }
  - { room: "1016",  ip: "192.168.1.44",  startIdx: 119, numLamps: 3, apiVersion: 2 }
  - { room: "1015",  ip: "192.168.1.45",  startIdx: 122, numLamps: 3, apiVersion: 2 }
  - { room: "1014",  ip: "192.168.1.46",  startIdx: 125, numLamps: 3, apiVersion: 2 }
  - { room: "1013",  ip: "192.168.1.47",  startIdx: 128, numLamps: 4, apiVersion: 2 }
  - { room: "1012",  ip: "192.168.1.48",  startIdx: 132, numLamps: 3, apiVersion: 2 }
  - { room: "1011",  ip: "192.168.1.49",  startIdx: 135, numLamps: 5, apiVersion: 2 }
  # 9th floor
  - { room: "919",   ip: "192.168.1.51",  startIdx: 140, numLamps: 2, apiVersion: 2 }
  - { room: "918",   ip: "192.168.1.52",  startIdx: 142, numLamps: 2, apiVersion: 2 }
  - { room: "917",   ip: "192.168.1.53",  startIdx: 144, numLamps: 2, apiVersion: 2 }
  - { room: "916",   ip: "192.168.1.54",  startIdx: 146, numLamps: 2, apiVersion: 2 }
  - { room: "915a",  ip: "192.168.1.55",  startIdx: 148, numLamps: 2, apiVersion: 2 }
  - { room: "915",   ip: "192.168.1.56",  startIdx: 150, numLamps: 3, apiVersion: 2 }
  - { room: "914",   ip: "192.168.1.57",  startIdx: 153, numLamps: 4, apiVersion: 2 }
  - { room: "913",   ip: "192.168.1.58",  startIdx: 157, numLamps: 2, apiVersion: 2 }
  - { room: "912",   ip: "192.168.1.59",  startIdx: 159, numLamps: 3, apiVersion: 2 }
  - { room: "911b",  ip: "192.168.1.60",  startIdx: 162, numLamps: 3, apiVersion: 2 }
  - { room: "911c",  ip: "192.168.1.61",  startIdx: 165, numLamps: 3, apiVersion: 2 }
  # 8th floor
  - { room: "818",   ip: "192.168.1.62",  startIdx: 168, numLamps: 2, apiVersion: 2 }
  - { room: "817b",  ip: "192.168.1.63",  startIdx: 170, numLamps: 2, apiVersion: 2 }
  - { room: "817a",   ip: "192.168.1.64",  startIdx: 172, numLamps: 2, apiVersion: 2 }
  - { room: "816",   ip: "192.168.1.65",  startIdx: 174, numLamps: 2, apiVersion: 2 }
  - { room: "815",   ip: "192.168.1.66",  startIdx: 176, numLamps: 2, apiVersion: 2 }
  - { room: "814",   ip: "192.168.1.67",  startIdx: 178, numLamps: 3, apiVersion: 2 }
  - { room: "813",   ip: "192.168.1.68",  startIdx: 181, numLamps: 3, apiVersion: 2 }
  - { room: "812",   ip: "192.168.1.69",  startIdx: 184, numLamps: 2, apiVersion: 2 }
  - { room: "811",   ip: "192.168.1.70",  startIdx: 186, numLamps: 3, apiVersion: 2 }
  - { room: "810a",  ip: "192.168.1.71",  startIdx: 189, numLamps: 4, apiVersion: 2 }
  - { room: "810",   ip: "192.168.1.72",  startIdx: 193, numLamps: 3, apiVersion: 2 }
  # 7th floor
  - { room: "715",   ip: "192.168.1.73",  startIdx: 196, numLamps: 6, apiVersion: 2 }
  - { room: "714",   ip: "192.168.1.74",  startIdx: 202, numLamps: 2, apiVersion: 2 }
  - { room: "713",   ip: "192.168.1.75",  startIdx: 204, numLamps: 2, apiVersion: 2 }
  - { room: "712",   ip: "192.168.1.76",  startIdx: 206, numLamps: 4, apiVersion: 2 }
  - { room: "711",   ip: "192.168.1.77",  startIdx: 210, numLamps: 4, apiVersion: 2 }
  - { room: "710",   ip: "192.168.1.78",  startIdx: 214, numLamps: 2, apiVersion: 2 }
  - { room: "709b",  ip: "192.168.1.79",  startIdx: 216, numLamps: 2, apiVersion: 2 }
  - { room: "709a",  ip: "192.168.1.80",  startIdx: 218, numLamps: 3, apiVersion: 2 }
  - { room: "709",   ip: "192.168.1.81",  startIdx: 221, numLamps: 3, apiVersion: 2 }
  # 6th floor
  - { room: "616",   ip: "192.168.1.82",  startIdx: 224, numLamps: 3, apiVersion: 1 }
  - { room: "615",   ip: "192.168.1.83",  startIdx: 227, numLamps: 2, apiVersion: 1 }
  - { room: "614a",  ip: "192.168.1.84",  startIdx: 229, numLamps: 2, apiVersion: 1 }
  - { room: "614",   ip: "192.168.1.85",  startIdx: 231, numLamps: 2, apiVersion: 1 }
  - { room: "613",   ip: "192.168.1.86",  startIdx: 233, numLamps: 3, apiVersion: 1 }
  - { room: "612",   ip: "192.168.1.87",  startIdx: 236, numLamps: 3, apiVersion: 1 }
  - { room: "611a",  ip: "192.168.1.88",  startIdx: 239, numLamps: 3, apiVersion: 1 }
  - { room: "611",   ip: "192.168.1.89",  startIdx: 242, numLamps: 3, apiVersion: 1 }
  - { room: "610a",  ip: "192.168.1.90",  startIdx: 245, numLamps: 2, apiVersion: 1 }
  - { room: "610",   ip: "192.168.1.91",  startIdx: 247, numLamps: 5, apiVersion: 1 }
  # 5th floor
  - { room: "519L",  ip: "192.168.1.93",  startIdx: 252, numLamps: 3, apiVersion: 1 }
  - { room: "519R",  ip: "192.168.1.94",  startIdx: 255, numLamps: 3, apiVersion: 1 }
  - { room: "518",   ip: "192.168.1.95", startIdx: 258, numLamps: 4, apiVersion: 1 } # TODO: change to ID 95
  - { room: "517",   ip: "192.168.1.96",  startIdx: 262, numLamps: 3, apiVersion: 1 }
  - { room: "516",   ip: "192.168.1.97",  startIdx: 265, numLamps: 3, apiVersion: 1 }
  - { room: "515",   ip: "192.168.1.98",  startIdx: 268, numLamps: 2, apiVersion: 1 }
  - { room: "514",   ip: "192.168.1.99",  startIdx: 270, numLamps: 3, apiVersion: 1 }
  - { room: "513",   ip: "192.168.1.100", startIdx: 273, numLamps: 2, apiVersion: 1 }
  - { room: "512b",  ip: "192.168.1.101", startIdx: 275, numLamps: 2, apiVersion: 1 }
  - { room: "512a",  ip: "192.168.1.102", startIdx: 277, numLamps: 3, apiVersion: 1 }
  # 4th floor
  - { room: "421",   ip: "192.168.1.103", startIdx: 280, numLamps: 4, apiVersion: 1 }
  - { room: "420",   ip: "192.168.1.104", startIdx: 284, numLamps: 2, apiVersion: 1 }
  - { room: "419",   ip: "192.168.1.105", startIdx: 286, numLamps: 3, apiVersion: 1 }
  - { room: "418",   ip: "192.168.1.106", startIdx: 289, numLamps: 2, apiVersion: 1 }
  - { room: "417",   ip: "192.168.1.107", startIdx: 291, numLamps: 3, apiVersion: 1 }
  - { room: "416",   ip: "192.168.1.108", startIdx: 294, numLamps: 3, apiVersion: 1 }
  - { room: "415",   ip: "192.168.1.109", startIdx: 297, numLamps: 3, apiVersion: 1 }
  - { room: "414",   ip: "192.168.1.110", startIdx: 300, numLamps: 4, apiVersion: 1 }
  - { room: "413",   ip: "192.168.1.111", startIdx: 304, numLamps: 4, apiVersion: 1 }
  # 3rd floor
  - { room: "315",   ip: "192.168.1.112", startIdx: 308, numLamps: 3, apiVersion: 1 }
  - { room: "314",   ip: "192.168.1.113", startIdx: 311, numLamps: 2, apiVersion: 1 }
  - { room: "313",   ip: "192.168.1.114", startIdx: 313, numLamps: 3, apiVersion: 1 }
  - { room: "312",   ip: "192.168.1.115", startIdx: 316, numLamps: 2, apiVersion: 1 }
  - { room: "311",   ip: "192.168.1.116", startIdx: 318, numLamps: 3, apiVersion: 1 }
  - { room: "310",   ip: "192.168.1.117", startIdx: 321, numLamps: 2, apiVersion: 1 }
  - { room: "309b",  ip: "192.168.1.118", startIdx: 323, numLamps: 2, apiVersion: 1 }
  - { room: "309a",  ip: "192.168.1.119", startIdx: 325, numLamps: 2, apiVersion: 1 }
  - { room: "307b",  ip: "192.168.1.120", startIdx: 327, numLamps: 2, apiVersion: 1 }
  - { room: "307a",  ip: "192.168.1.121", startIdx: 329, numLamps: 2, apiVersion: 1 }
  - { room: "306",   ip: "192.168.1.122", startIdx: 331, numLamps: 2, apiVersion: 1 }
  - { room: "305",   ip: "192.168.1.123", startIdx: 333, numLamps: 3, apiVersion: 1 }
  # 2nd floor
  - { room: "219",   ip: "192.168.1.124", startIdx: 336, numLamps: 3, apiVersion: 1 }
  - { room: "218",   ip: "192.168.1.125", startIdx: 339, numLamps: 2, apiVersion: 1 }
  - { room: "217",   ip: "192.168.1.126", startIdx: 341, numLamps: 3, apiVersion: 1 }
  - { room: "216",   ip: "192.168.1.127", startIdx: 344, numLamps: 2, apiVersion: 1 }
  - { room: "215",   ip: "192.168.1.128", startIdx: 346, numLamps: 2, apiVersion: 1 }
  - { room: "214",   ip: "192.168.1.129", startIdx: 348, numLamps: 3, apiVersion: 1 }
  - { room: "213",   ip: "192.168.1.130", startIdx: 351, numLamps: 2, apiVersion: 1 }
  - { room: "212",   ip: "192.168.1.131", startIdx: 353, numLamps: 3, apiVersion: 1 }
  - { room: "211",   ip: "192.168.1.132", startIdx: 356, numLamps: 3, apiVersion: 1 }
  - { room: "210",   ip: "192.168.1.133", startIdx: 359, numLamps: 2, apiVersion: 1 }
  - { room: "209",   ip: "192.168.1.134", startIdx: 361, numLamps: 3, apiVersion: 1 }
  # 1st floor
  - { room: "114",   ip: "192.168.1.135", startIdx: 364, numLamps: 3, apiVersion: 1 }
  - { room: "113L",  ip: "192.168.1.136", startIdx: 367, numLamps: 3, apiVersion: 1 }
  - { room: "113R",  ip: "192.168.1.137", startIdx: 370, numLamps: 3, apiVersion: 1 }
  - { room: "112a",  ip: "192.168.1.138", startIdx: 373, numLamps: 3, apiVersion: 1 }
  - { room: "112",   ip: "192.168.1.139", startIdx: 376, numLamps: 2, apiVersion: 1 }
  - { room: "111",   ip: "192.168.1.140", startIdx: 378, numLamps: 3, apiVersion: 1 }
  - { room: "110",   ip: "192.168.1.141", startIdx: 381, numLamps: 4, apiVersion: 1 }
  - { room: "109",   ip: "192.168.1.142", startIdx: 385, numLamps: 2, apiVersion: 1 }
  - { room: "108",   ip: "192.168.1.143", startIdx: 387, numLamps: 2, apiVersion: 1 }
  - { room: "107",   ip: "192.168.1.144", startIdx: 389, numLamps: 3, apiVersion: 1 }
